#!/usr/bin/env python3
"""Regenerate wiki/index.md from every wiki file's frontmatter.

The index is the agent's navigation map. Rather than hand-maintain it on
every write, derive it: each entry is `[[slug|Title]] — summary`, grouped by
directory, with `[stub]` / `[DM-only]` markers read from frontmatter. Ordering
is deterministic (priority groups, then slug-sorted) so reruns are stable.

Usage:
    regen_index.py            # print to stdout (dry run)
    regen_index.py --write    # rewrite wiki/index.md in place
"""

from __future__ import annotations

import os
import re
import sys

from wiki_common import (
    WIKI_DIR,
    first_h1,
    iter_wiki_files,
    parse_fields,
    rel,
    split_frontmatter,
    today,
)

# Bookkeeping files are not catalogue targets — skip them.
SKIP_BASENAMES = {
    "index.md", "log.md", "work-queue.md",
    "discrepancy-log.md",
}

# Group display order. Anything unlisted sorts alphabetically after these.
GROUP_PRIORITY = [
    "entities/characters/pcs",
    "entities/characters/npcs",
    "entities/characters/crew",
    "entities/characters/minor",
    "entities/places",
    "entities/factions",
    "entities/deities",
    "entities/items",
    "entities/vehicles",
    "situations/active",
    "situations/dormant",
    "situations/resolved",
    "islands",
    "lore",
    "rules",
    "sessions",
    "system",
    "dm",
]


def slug_of(path: str) -> str:
    return os.path.splitext(os.path.basename(path))[0]


def title_of(slug: str, body: str) -> str:
    h1 = first_h1(body)
    if h1:
        return h1
    return " ".join(w.capitalize() for w in slug.split("-"))


def marker_of(fields: dict) -> str:
    status = fields.get("status", "").strip()
    subtype = fields.get("subtype", "").strip()
    tags = fields.get("tags", "")
    is_stub = status == "stub"
    dm_only = subtype == "secret" or "dm-only" in tags or "dm-secret" in tags
    if dm_only and is_stub:
        return "[DM-only stub] "
    if dm_only:
        return "[DM-only] "
    if is_stub:
        return "[stub] "
    return ""


def group_key(relpath: str) -> str:
    # relpath like "wiki/entities/characters/pcs/foo.md" -> group dir
    d = os.path.dirname(relpath[len("wiki/"):])
    return d if d else "(root)"


def group_sort_key(group: str):
    for i, prefix in enumerate(GROUP_PRIORITY):
        if group == prefix or group.startswith(prefix + "/"):
            return (0, i, group)
    return (1, 0, group)


def build() -> str:
    groups: dict[str, list[tuple[str, str]]] = {}
    for path in iter_wiki_files():
        if os.path.basename(path) in SKIP_BASENAMES:
            continue
        relpath = rel(path)
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        fm_lines, body, _ = split_frontmatter(text)
        fields = parse_fields(fm_lines)
        slug = slug_of(path)
        title = title_of(slug, body)
        summary = fields.get("summary", "").strip().strip('"').strip("'")
        marker = marker_of(fields)
        entry = f"- [[{slug}|{title}]] — {marker}{summary}".rstrip()
        groups.setdefault(group_key(relpath), []).append((slug, entry))

    out = []
    for group in sorted(groups, key=group_sort_key):
        out.append(f"## {group}")
        for _slug, entry in sorted(groups[group]):
            out.append(entry)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


HEADER = """---
type: system
subtype: index
campaign: shattered-sea
status: active
audience: agent
publish: false
summary: "Master catalog of all wiki files. Grouped by path. Auto-generated by regen_index.py — do not hand-edit."
created: 2026-05-27
updated: {today}
tags: [system, index]
sources: []
---

# Wiki Index — Shattered Sea

"""


def main(argv) -> int:
    body = build()
    full = HEADER.format(today=today()) + body
    if "--write" in argv:
        with open(os.path.join(WIKI_DIR, "index.md"), "w", encoding="utf-8") as fh:
            fh.write(full)
        sys.stderr.write("regen_index: wrote wiki/index.md\n")
    else:
        sys.stdout.write(full)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
